---
- name: Simple Apache Web Server Setup
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache (Ubuntu)
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple index.html page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from Ansible</h1>"
